name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
          cache: false


      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: update-docs-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            update-docs-${{ runner.os }}-go-

      - name: Build
        run: go build
